# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
###
#name: Deploy to AWS S3

#on:
#  push:
#    branches:
 #     - master

#jobs:
#  build_and_deploy:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: [16.x]
#    # steps represent a sequence of tasks that will be executed as part of the job
#    steps:
#      - uses: actions/checkout@v3
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ matrix.node-version }}

#      - name: NPM Install
#        run: npm install
#      # Create production build
#      - name: Build Website
#        run: npm run build -- -c production
#      # Deploy to S3
#      - name: Deploy to AWS S3
#        uses: jakejarvis/s3-sync-action@v0.5.1
#        with:
#          args: --acl public-read --delete
#       env:
#          AWS_S3_BUCKET: ${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
#          AWS-REGION: us-est-13
#          SOURCE_DIR: "dist/front-ecomm"

